# fly.toml app configuration file generated for crudcleiton on 2024-10-05T19:48:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crudcleiton'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
